name: TCBee build

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y llvm clang libelf-dev libclang-dev
        cargo install bpf-linker

    - name: TCBee Build
      run: cd tcbee && cargo build --release

    - name: DB Build
      run: cd db && cargo build --release

    - name: Visualization Build
      run: cd viz-tool && cargo build --release      